version: '2'

tasks:
  setup-buildx:
    desc: Setup Binfmt and buildx builder
    cmds:
      - docker run --rm --privileged docker/binfmt:{{ .BINFMTSHA }}
      - mkdir -p $HOME/.docker/cli-plugins/
      - curl -Lo $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
      - docker buildx create --name builder
      - docker buildx use builder

  cleanup-buildx:
    desc: Cleanup buildx builder
    cmds:
      - docker buildx rm builder

  buildx-registry:
    cmds:
      - cd {{ .DIR }} && docker buildx build --platform {{ .PLATFORMS }} -f Dockerfile {{ .BUILD_ARGS }} --build-arg ENTRYPOINT_VERSION={{ .ENTRYPOINT_VERSION}} --build-arg DEBIANTAG={{ .DEBIANTAG }} -t primeroz/{{ .DIR }}:{{ .TAG }} --push .

  bitcoind:
    desc: Build BitcoinD images
    cmds:
      - task: buildx-registry
        vars: 
          PLATFORMS: "{{ .PLATFORMS }}"
          DIR: "{{ .BITCOIND_DIR }}"
          TAG: "{{ .BITCOIND_TAG }}"
          BUILD_ARGS: "--build-arg BITCOIND_VERSION={{ .BITCOIND_VERSION }}"

  tor:
    desc: Build Tor images
    cmds:
      - task: buildx-registry
        vars:
          PLATFORMS: "{{ .PLATFORMS }}"
          DIR: "{{ .TOR_DIR }}"
          TAG: "{{ .TOR_TAG }}"
          BUILD_ARGS: "--build-arg tor_version={{ .TOR_VERSION }}"

  electrs:
    desc: Build Electrs images
    cmds:
      - task: buildx-registry
        vars: 
          PLATFORMS: "{{ .PLATFORMS }}"
          DIR: "{{ .ELECTRS_DIR }}"
          TAG: "{{ .ELECTRS_TAG }}"
          BUILD_ARGS: "--build-arg electrs_version={{ .ELECTRS_VERSION }}"
